// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2017.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4579.Robot2017.Robot;
import org.opencv.core.*;

import java.util.List;
import java.util.ArrayList; //I DONT KNOW WHY WE NEED TWO PACKAGES TO GET ONE THING BUT OOOOOOK

/**
 *
 */
public class FindPeg extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	private ArrayList<MatOfPoint> contours = new ArrayList<>();
    public FindPeg() {
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.cam);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.cam.initCamera();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.cam.updateContours();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	contours = Robot.cam.getContours();
    	if (contours.size() == 2) {
    		/* 
    		 *  At this point, if the two tapes are found, then the command ends and no more frames are updated.
    		 *  The next command will handle processing the tape.
    		 */
    		System.out.println("Found two tapes");
    		
    		return true;
    	} else if (contours.size() == 1) {
    		/*
    		 *  Get which direction and angle the contour is at
    		 *  Rotate the robot in the direction of the tape
    		 *  Note: This is only useful when starting the robot for the first time, if one of the tapes
    		 */
    		return false;
    	} else {
    		/* 
    		 *  There are 0 or 3+ contours
    		 *  Keep rotating in the same direction, until a certain point
    		 *  At that point, reverse the direction and search the other side.
    		 */
    		return false;
    	}
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
