// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay cameraLight;
    public static SpeedController driveTraincontrollerLeft;
    public static SpeedController driveTraincontrollerRight;
    public static RobotDrive driveTrainRobotDrive;
    public static Ultrasonic ultrasonicSensorultraLeft;
    public static Ultrasonic ultrasonicSensorultraRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        cameraLight = new Relay(0);
        LiveWindow.addActuator("Camera", "Light", cameraLight);
        
        driveTraincontrollerLeft = new VictorSP(9);
        LiveWindow.addActuator("DriveTrain", "controllerLeft", (VictorSP) driveTraincontrollerLeft);
        
        driveTraincontrollerRight = new VictorSP(8);
        LiveWindow.addActuator("DriveTrain", "controllerRight", (VictorSP) driveTraincontrollerRight);
        
        driveTrainRobotDrive = new RobotDrive(driveTraincontrollerLeft, driveTraincontrollerRight);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        ultrasonicSensorultraLeft = new Ultrasonic(0, 1);
        LiveWindow.addSensor("UltrasonicSensor", "ultraLeft", ultrasonicSensorultraLeft);
        
        ultrasonicSensorultraRight = new Ultrasonic(2, 3);
        LiveWindow.addSensor("UltrasonicSensor", "ultraRight", ultrasonicSensorultraRight);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
