// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2017.subsystems;

import org.usfirst.frc4579.Robot2017.Robot;
import org.usfirst.frc4579.Robot2017.RobotMap;
import org.usfirst.frc4579.Robot2017.commands.*;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class DriveTrain extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController controllerLeft = RobotMap.driveTraincontrollerLeft;
    private final SpeedController controllerRight = RobotMap.driveTraincontrollerRight;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public int drive_direction = 1;
    public String pidMode = "rotate";
    public final double TURN_SPEED = 0.6; //Used for continuousDrive();

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public DriveTrain() {
    	super("DriveTrain", 2.0, 0.0, 0.0, 0.6);// TODO: GET THIS DAMN THING TUNED
		setAbsoluteTolerance(1.0);
		setInputRange(0.0, 360.0); //If we need to get the PID for driving instead of rotating, we could possibly change this+ other things
		setOutputRange(0.0,1.0);
		getPIDController().setContinuous(true);
    }
    // Return true if the motors are commanded to zero.
    public boolean isNotMoving() {
    	return (controllerLeft.get() == 0.0) && (controllerRight.get() == 0.0);
    }
    
    // Drive each motor at the indicated speed.
    public void driveEachMotor (double leftMotorSpeed, double rightMotorSpeed) {

    	controllerLeft .set(leftMotorSpeed);
    	controllerRight.set(rightMotorSpeed);
    	
    }
    
    public void drive() {
    	double x = Robot.oi.joystick.getX();//*drive_direction;
    	double y = Robot.oi.joystick.getY();//*drive_direction;
    	double xsign = Math.signum(x);
    	double ysign = Math.signum(y);
    	final double slider = Robot.oi.joystick.getRawAxis(2) / 2;
    	double sensitivity = 0.5 - slider;
    	robotDrive.arcadeDrive(Math.pow(x*sensitivity, 2)*xsign, Math.pow(y*sensitivity, 2)*ysign*drive_direction);
    	//robotDrive.arcadeDrive(Math.pow(x*sensitivity, 2)*xsign, Math.pow(y*sensitivity, 2)*ysign);
    }
    // Turns the robot continuously either left or right. Speed may need to change.
    
    public void stop(){
    	controllerLeft.stopMotor();
    	controllerRight.stopMotor();
    }
    //BACKWARDS DRIVE METHODS
    public void reverseDrive() {
    	System.out.println("Setting drive to reverse");
    	drive_direction = -1;
    }
    public void forwardDrive() {
    	System.out.println("Setting drive to forward");
    	drive_direction = 1;
    }
    //PID methods
    public void continuousTurn(String dir) {
    	double negator = 1;
    	if (dir == "left") {
    		negator = -1;
    	}
    	robotDrive.tankDrive(TURN_SPEED*negator, -TURN_SPEED*negator); //if left turn, LEFT:NEG, RIGHT:POS. if right turn, LEFT:POS, RIGHT:NEG.
    }
    //Sets the goal for the PID system to reach
    public void setSetpoint(double angle) {
    	getPIDController().setSetpoint(angle);
    }
    public boolean isAtSetpoint() {
    	return getPIDController().onTarget();
    }
    //Enables the PID controller, this starts the PID controller.
    public void driveToSetpoint() {
    	if (!getPIDController().isEnabled()) {
    		getPIDController().enable();
    	}
    }
    //Enable the PID controller with a specified angle/distance. Overloaded method. Not sure I need this method though.
    public void driveToSetpoint(double angle) {
    	setSetpoint(angle);
    	if (!getPIDController().isEnabled()) {
    		getPIDController().enable();
    	}
    }
    //Stops PID controller. Calls disable, resets error/integral term.
    public void stopDrivingToSetpoint() {
    	getPIDController().reset();
    }
    public void shiftPIDToDrive() {
    	if (!getPIDController().isEnabled()) {
    		pidMode = "drive";
    		// I could probably set the PIDController method to a variable...if I weren't so paranoid...
    		getPIDController().reset();
    		getPIDController().setContinuous(false);
    		getPIDController().setInputRange(minimumInput, maximumInput);
    		getPIDController().setPID(2.0, 0, 0, 0);
    		setAbsoluteTolerance(1.0);
    	} else {
    		System.out.println("Error: Can't shift, PIDController is busy.");
    	}
    }
    public void shiftPIDToRotate() {
    	if (!getPIDController().isEnabled()) {
    		pidMode = "rotate";
    		// I could probably set the PIDController method to a variable...if I weren't so paranoid...
    		getPIDController().reset();
    		getPIDController().setContinuous(true);
    		getPIDController().setInputRange(minimumInput, maximumInput);
    		getPIDController().setPID(2.0, 0, 0, 0.6);
    		setAbsoluteTolerance(1.0);
    	} else {
    		System.out.println("Error: Can't shift, PIDController is busy.");
    	}
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DefaultDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public double returnPIDInput() {
    	double output = 0;
    	if (pidMode == "rotate") {
    		output = angle = 90.0; //Robot.meas.getAngle() % 360; //Since setContinuous treats the beginning and end as the same, there isn't a problem with 359/1.
    	} else if (pidMode == "drive") {
    		
    	}
    	return angle;
    }
    public void usePIDOutput(double output) {
    	if (pidMode == "rotate") {
    		robotDrive.tankDrive(output, -output);//left right respectively
    	} else if (pidMode == "drive") {
    		robotDrive.arcadeDrive(output, 0);
    	}
    	SmartDashboard.putData("PID Controller",controller);
    }
}
